name: CLA Assistant

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, synchronize, reopened, closed]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write

jobs:
  cla:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'pull_request_target')
      || (github.event_name == 'issue_comment' && github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA')
    steps:
      - name: CLA Assistant
        uses: contributor-assistant/github-action@v2
        with:
          path-to-signatures: signatures/cla.json
          path-to-document: https://github.com/SixFive7/BoundedPriorityChannel/blob/main/CLA.md
          branch: main
          allowlist: dependabot[bot],github-actions[bot]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
